import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/share/Navbar";
import FooterPage from "@/components/share/Footer";
import { ToastContainer } from "react-toastify";
import PracticeProvider from "@/context/PracticeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <PracticeProvider>
          <Navbar />
          
          <main className="flex-1">{children}</main>
<FooterPage />
          <ToastContainer />
        </PracticeProvider>
      </body>
    </html>
  );
}
